- ec2:
    key_name: "{{ec2_key_name}}"
    instance_type: "{{ec2_instance_type}}"
    image: "{{ami_id}}"
    group: "{{ec2_security_group}}"
    instance_tags: 
      Name: "{{app_name}}-{{ ansible_date_time.iso8601 | regex_replace('[^a-zA-Z0-9]', '-') }}"
    vpc_subnet_id: "{{ec2_subnet}}"
    region: "{{ec2_region}}"
    assign_public_ip: "{{assign_public_ip}}"
    wait: yes
  register: ec2
  
- add_host: 
    hostname: "{{item.private_ip}}" 
    groupname: launched
  with_items: "{{ec2.instances}}"
  when: not assign_public_ip

- add_host: 
    hostname: "{{item.public_ip}}" 
    groupname: launched
  with_items: "{{ec2.instances}}"
  when: assign_public_ip

- debug:
    msg: "{{ec2}}"

- ec2_tag:
    region: "{{ec2_region}}"
    resource: "{{item.id}}"
    tags: "{{ec2_tags}}"
    state: present
  with_items: "{{ec2.instances}}"
  when: ec2_tags is defined

- ec2_vol:
    region: "{{ec2_region}}"
    instance: "{{ item.id }} "
    volume_size: "{{ec2_volume_size}}"
    volume_type: gp2
  with_items: "{{ec2.instances}}"
  when: ec2_volume_size is defined

- wait_for: 
    host: "{{item.private_ip}}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ec2.instances}}"
  when: not assign_public_ip

- wait_for: 
    host: "{{item.public_ip}}"
    port: 22
    delay: 60
    timeout: 320
    state: started
  with_items: "{{ec2.instances}}"
  when: assign_public_ip

